name: 09-strategy-single
on:
  push:

jobs:
  greeting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        property_1: ['a', 'b', 'c']
        property_2: ['1', '2', '3']
    steps:
      - name: Echo hello world
        run: echo "Hello, world $PROPERTY_1 $PRROPERTY2"
        env:
            PROPERTY1: ${{ matrix.property_1 }}
            PROPERTY2: ${{ matrix.property_2 }}