name: 14-literal-exchange
on:
  push:
  workflow_dispatch:

jobs:
  jobSource:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "::set-output name=varInStep::hello world"  
    outputs:
      greeting: ${{ steps.step1.outputs.varInStep }}
  jobTarget:
    runs-on: ubuntu-latest
    needs: jobSource
    steps:
      - run: echo ${{needs.jobSource.outputs.greeting}}