name: 15-share-artifact
on:
  push:
  workflow_dispatch:
jobs:
  jobSource:
    runs-on: ubuntu-latest
    steps:
      - name: "Create File"
        run: echo "Hello world" >> hello_world.txt
      - name: "Upload file"
        uses: actions/upload-artifact@v4
        with:
            name: greeting
            path: ./hello_world.txt
  jobTarget:
    runs-on: ubuntu-latest
    needs: jobSource
    steps:
      - name: "Download file"
        uses: actions/download-artifact@v4
        with:
          name: greeting
          path: ./greeting.txt
      - run: cat ./greeting.txt 
