name: 22-k8s-kubeconfig
on:
  push:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: gw-message-demo
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: azure/setup-kubectl@v4
        - uses: azure/k8s-set-context@v1
          with:
            method: kubeconfig
            context: 'default'
            kubeconfig: ${{ secrets.KUBECONFIG_EXAMPLE }}
        - uses: azure/k8s-deploy@v5
          with:
            manifests: |
              ./Manifest/deployment.yaml
            namespace: 'teilnehmer-04'
        - uses: actions/checkout@v3

      